#!/bin/sh

export WINIT_X11_SCALE_FACTOR=1

xrandr --dpi 96

xset r rate 300 50 &

xsetroot -cursor_name left_ptr &

xset s 300 5 &
xss-lock -n /usr/lib/xsecurelock/dimmer -l -- xsecurelock &

setxkbmap us,se -option caps:escape &

autostart="dunst pipewire"
for program in $autostart; do
	pidof -s "$program" || "program" &
done >/dev/null 2>&1
