theme = "boring"

[editor]
line-number = "relative"
mouse = false
cursorline = false
bufferline = "multiple"
color-modes = true
true-color = true

[editor.lsp]
display-inlay-hints = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["mode", "file-name"]
center = ["spinner"]
right = ["selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"

[editor.indent-guides]
render = true

[keys.normal]
# File picker using lf-pick (custom script). Set the theme at the end to trigger UI reload -- need to change to a different theme first.
C-f = [":new", ":insert-output lf-pick", ":theme default", "select_all", "split_selection_on_newline", "goto_file", "goto_last_modified_file", ":buffer-close!", ":theme boring"]
X = "extend_line_above"
# Using the arrow keys is not allowed.
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
pageup = "no_op"
pagedown = "no_op"
home = "no_op"
end = "no_op"

[keys.normal.space]
q = ":quit"
w = ":write"

[keys.insert]
# Using the arrow keys is not allowed.
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
pageup = "no_op"
pagedown = "no_op"
home = "no_op"
end = "no_op"