#!/bin/bash

SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

sxhkd &

flameshot &

eww daemon &

if [ -x "$(command -v picom)" ]; then
  picom --config ~/.config/picom/picom.conf &
fi

# Set background
if [ -x "$(command -v feh)" ]; then
  feh -no-fehbg --bg-scale $SCRIPTPATH/background.jpg
fi

eww open bar_primary
[[ "$(secondarymonitor)" != "" ]] && eww open bar_secondary

systemctl --user restart emacs
