#!/bin/bash

SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

sxhkd &

eww daemon &

if [ -x "$(command -v picom)" ]; then
  picom --config ~/.config/picom/picom.conf &
fi

# Set background
if [ -x "$(command -v feh)" ]; then
  feh --bg-scale $SCRIPTPATH/background.jpg
fi

eww open bar_primary
[[ "$(secondarymonitor)" != "" ]] && eww open bar_secondary
